# Generated by Django 4.1.3 on 2022-12-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageboard',
            name='posttime',
            field=models.TimeField(auto_now=True),
        ),
    ]
